### ISSUE TITLE
When will scan and review c# solutions?

### ISSUE THREAD

**Issue by johnfelipe** [Bearer/bearer#1095]

**Comment by cfabianski** [comment]
Hey @johnfelipe 
Could you be more explicit and update the description please 🙏🏼?

**Comment by johnfelipe** [comment]
i want to know if i can scan c# solution with your app, somethin
like fluidattacks or sonarqube?

**Comment by cfabianski** [comment]
We don't support C# for the SAST for now but you can use bearer to get the dataflow report (`bearer scan . --report dataflow`) or the [privacy](https://docs.bearer.com/guides/privacy/) report (`bearer scan . --report privacy`)
See https://docs.bearer.com/reference/supported-languages/

Closing that issue for now
