### ISSUE TITLE
Bearer detects CWE-693 even after disabling x-powered-by header

### ISSUE THREAD

**Issue by pathak-abhinav** [Bearer/bearer#1114]
## Description & Reproduction
Upon running the below command for a node.js project
```bash
bearer scan .
```
bearer detects `HIGH: Security misconfiguration detected. [CWE-693]` vulnerability.

![Screenshot from 2023-07-12 21-52-20](https://github.com/Bearer/bearer/assets/56205250/e52058d2-7d7d-421d-b9f3-8deec9fea144)

After using [this](https://docs.bearer.com/reference/rules/javascript_express_reduce_fingerprint) and [this](https://stackoverflow.com/questions/10717685/how-to-remove-x-powered-by-in-expressjs) article as reference, I have tried both the below mentioned approaches.

## Approach 1: disabling the header
```javascript
app.disable('x-powered-by');
```

## Approach 2: removing the header by middleware
```javascript
app.use(function (req, res, next) {
  res.removeHeader("X-Powered-By");
  next();
});
```
Can someone help me rectify if I am doing something wrong or is it a problem with bearer being unable to detect the fix for `CWE-693`?
The bearer version I am using is `v1.16.0` 

Currently, I have skipped the rule to get around it by using 
```yml
skip-rule: ['javascript_express_reduce_fingerprint']
```

## Expected Behavior

`CWE-693` should not be flagged anymore after disabling the header.

## Actual Behavior

`CWE-693` is still being flagged

## Your Environment

- Operating System and version: Ubuntu 20.04
- Output of 'bearer version': 
```
bearer version: 1.16.0
sha: 58b86f78c052ff1a5bc5f25baf633025aa6a7349
```

**Comment by elsapet** [comment]
Thanks for raising this @absum11 🐻 🙏 

I can reproduce this on my side. It looks likes a little issue with our `javascript_express_reduce_fingerprint` rule. We'll take a look and keep this thread updated. 

In the meanwhile, skipping the rule as you are doing is the best workaround.

**Comment by pathak-abhinav** [comment]
Hi @elsapet ,

Are there any active plans for fixing this?

**Comment by elsapet** [comment]
Hey @absum11, I am currently looking into the issue. I was unfortunately mistaken earlier, however, and I cannot in fact reproduce the issue. We have [two JS rules with duplicate titles](https://github.com/Bearer/bearer-rules/pull/142) and this confused me 😅 

Would you be able to share a code snippet that reproduces the issue for you (using Approach 1, disabling the header, if possible), and I can investigate further?

Many thanks 🙏

**Comment by pathak-abhinav** [comment]
Shall I provide you access to my project repository or is there any other means by which you want me to share (steps to reproduce the issue or code) that would be convenient to you?

**Comment by elsapet** [comment]
Thanks @absum11 - if you are willing and able to provide me with access to your project repo, this would be a great help!

**Comment by pathak-abhinav** [comment]
@elsapet  Please find the code [here](https://github.com/absum11/School2)

## Steps to reproduce
1. Clone the repository
2. Make sure that you are on the following version of bearer 

```bash
bearer version: 1.16.0
sha: 58b86f78c052ff1a5bc5f25baf633025aa6a7349
```
3. Make sure your pwd is `school2`
4.  Run the following command to initiate a scan

```bash
bearer scan .
```

## Output on my machine
```bash
Loading rules
Using cached data
Running Detectors
Generating dataflow
Evaluating rules
 └ 100% [===============] (175/175, 54 rules/s) [3s]   


Security Report

=====================================

Rules: 
 - 72 default rules applied (https://docs.bearer.com/reference/rules) []


HIGH: Security misconfiguration detected. [CWE-693]
https://docs.bearer.com/reference/rules/javascript_express_reduce_fingerprint
To exclude this finding, use the flag --exclude-fingerprint=f6ffb063d44eb3007f0754a450f6e2f1_0

File: src/src/app.js:8


=====================================

72 checks, 1 findings

CRITICAL: 0
HIGH: 1 (CWE-693)
MEDIUM: 0
LOW: 0
WARNING: 0

Need help or want to discuss the output? Join the Community https://discord.gg/eaHZBJUXRF

Ready to take the next step, learn more about Bearer Cloud https://www.bearer.com/bearer-cloud
```

**Comment by pathak-abhinav** [comment]
@elsapet  When I re-ran the scan now, it worked. I am so confused as to why it did not work earlier.

**Comment by elsapet** [comment]
Thanks @absum11 for sharing your code and repro steps 🙏  

It’s working for me too, and it's curious that it wasn't earlier. From our side, we haven’t released any Bearer or Bearer Rule updates (aside from [a small docs change](https://github.com/Bearer/bearer-rules/releases/tag/v0.18.1)). 

One possible cause that I can think of, if you were working on a local machine, is that perhaps some scans were run using cached data, and any uncommitted code changes were not picked up. This is the default behaviour: Bearer will only do a full re-scan if the git SHA has changed. This can be overridden by using the `—force` flag, which will ensure a full re-scan is done regardless of whether or not the SHA has changed: 

```
 ⇒  bearer scan . —force
```

As a note, we should be displaying clearer messaging about when cached data is used. I've raised a bug about this and will be addressing it in our current cycle (this week): https://github.com/Bearer/bearer/issues/1120

Thanks again for your help investigating this and bringing it to our attention. I'll let you close this issue if you're happy with the `javascript_express_reduce_fingerprint` rule  🙏  🐻

**Comment by pathak-abhinav** [comment]
Thanks for your support @elsapet 

I am satisfied with the reply that you have provided. I'll go ahead and close this issue. 

Yes, it would be quite helpful to add a small message at the end of each scan about cache data being used and using the --force option to ensure any such cached data is not picked up. 

I will follow up on your thread regarding this bug.
