### ISSUE TITLE
Allow failures without exiting with an error code

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#1119]
Today when the CLI run it exits with a fail status code (-1) when a finding is found, this is a good default behavior.
But, it's not always enough, especially when starting to implement such a solution into a CI/CD workflow, you don't necessarily want to fail it but only want to be able to see the report. 

For that reason, it would be important to add a new flag that disables failed status code whenever a finding is reported, for e.g:
```bearer scan . --allow_failure```

For reference, GitLab CI allow such behavior (cf [doc](https://docs.gitlab.com/ee/ci/yaml/#allow_failure)) but not GitHub Action, so it's probably better to bake such solution natively in Bearer CLI.

_PS: This need has been reported by a user._

**Comment by joevin-slq-docto** [comment]
In a similar way, if you decide one day to implement the concept of "confidence" to help sort alerts.
It might be interesting to make the CLI status code taking in to account the level of "confidence", and make this threshold customizable.

But things get more complex when GitHub integration is involved.
Especially when `reviewdog` is used (cf [doc](https://docs.bearer.com/guides/github-action/#code-review-comments)). In that case, Bearer rdjson output will need to match Reviewdog levels (info, warning, error) to obtain the desired behavior assigned to the bearer CLI (ex. `bearer scan . --fail-above-severity high,medium,low --fail-above-confidence high`).

With the example above, a high severity bearer alert with a low confidence will become 'info' in the rdjson file, and a medium with a high confidence will become an error in the rdjson file.

**Comment by gotbadger** [comment]
@gmontard github actions do support this behaviour through `continue-on-error: true`

Its usage can be seen in the reviewdog example:
https://github.com/Bearer/bearer-action#using-reviewdog-for-pr-review-comments-with-bearer

There are many ways/things that might make a user want to fail a process or not IMO its easier to let them make a call on that by looking at the output. Maybe some other reason we want to force exit code?

**Comment by gotbadger** [comment]
we had a chat and found that `continue-on-error: true` will still mark the job as a red x in github so its easier if there is just a simple flag to make it always pass.
