### ISSUE TITLE
Improve ignore managment

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#1173]
Current ignore format dosen't contain much information which makes management difficult.

We would like to improve how findings are managed. 

Introduce bearer.ignore to contain ignored items format would look like:

```
{
  findingId: {
   author:
   comment:
   ignoredAt:
  
  }
  ...
}
```

Add some convenience commands to interact:

```
$ bearer ignore add FINDING_ID —comment=“My message” -author=“Me”
```

```
$ bearer ignore show FINDING_ID

Ignored At: <Timestamp>
Author: Me

My message

```

Comment and author are optional so we can migrate existing ingore files

Would be helpful to have some method to migrate for users to this new format.

**Comment by cfabianski** [comment]
Main issue I see is that you would need to have a way to specify what's the root of the folder otherwise you might end up with several bearer.ignore files (one in each folder) depending on how and where you run the command 🤔
