### ISSUE TITLE
Open source claim is false

### ISSUE THREAD

**Issue by illiliti** [Bearer/bearer#1183]
The license of this project is incompatible with the [open-source definition](https://opensource.org/osd/). It limits field of endeavor by prohibiting provision to third parties as a hosted or managed service without explicit approval and hence cannot be considered open-source. Therefore I request to remove all false advertising about open-source or, as alternative option, relicense this project to an open-source license of your choice.

**Comment by gmontard** [comment]
Closing this ticket, terminology change as been updated.

**Comment by illiliti** [comment]
If bearer was a **free** house with door **open** for everyone, then I would not object to this terminology. However since bearer is a software where "free" and "open" have well-known and estabilished meaning, I still find choosen terminology misleading. It would be great to not play with words and choose better term which describes your software. How about source-available[^1]? Or fair-code[^2]?

[^1]: https://en.wikipedia.org/wiki/Source-available_software
[^2]: https://faircode.io/

Besides that, bearer.com still mentions that bearer is open-source. That needs retraction as well. EDIT: bearer-cli-overview-cc.mp4 also contains open-source mention.

**Comment by gmontard** [comment]
I can understand why you may disagree with the terminology "Free and Open", but as we are not professional legal experts on the topic, we defer any comment directly to [Elastic](https://github.com/elastic/elasticsearch) considering we're using their License and therefore terminology. They surely have spent a lot of time and money on it with professional legal experts.

Nonetheless, we appreciate your feedback, thank you again. 

_PS: Updates on the company website haven't been released yet, but this repo has nothing to do with it._

**Comment by illiliti** [comment]
> I can understand why you may disagree with the terminology "Free and Open", but as we are not professional legal experts on the topic, we defer any comment directly to [Elastic](https://github.com/elastic/elasticsearch) considering we're using their License and therefore terminology. They surely have spent a lot of time and money on it with professional legal experts.

Elastic is deliberately advertising itself as "Free and Open" in order to attract people who don't know about Elastic dark past and who confuse their terminology with well-known and widely accepted free software and open-source terms, also known as _Free and Open source software_(notice similarity). They are using this shady deceptive method for their marketing purposes only to extract more value from those who unaware. What is this if not fraudulence?

As of our case, you decide whether you want to be a part of this by continuing misleading people into believing that your software is FOSS using deceptive terms, or you want to be fair, concise and clear about your software by using terms(e.g those that I listed) which do not have similarity or connotation with Free and Open source software. Think wisely before picking your side.

> PS: Updates on the company website haven't been released yet, but this repo has nothing to do with it.

Looking forward to see those updates. Also don't forget to update bearer-cli-overview-cc.mp4 in README.md to retract open-source claim.
