### ISSUE TITLE
Failed to send data to Bearer Cloud. Unable to calculate Metadata. exit status 128

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#1196]
## Description & Reproduction

When performing a scan with an API key we receive the following error
`Failed to send data to Bearer Cloud. Unable to calculate Metadata. exit status 128`

Error is happening when a repository has a local git HEAD but no origin/HEAD 
This is breaking `getDefaultBranch()` in `saas.go`

**Comment by gmontard** [comment]
Can we add a nice warning message as a CLI output with indication on what to do for the user @cfabianski ?

**Comment by cfabianski** [comment]
> Can we add a nice warning message as a CLI output with indication on what to do for the user @cfabianski ?

@gmontard We have a message (debug) for this but maybe debug isn't enough https://github.com/Bearer/bearer/blob/5073de85f13477f86f2ee79a3f63ceb5e03b6dd1/pkg/report/output/saas/saas.go#L223
🤔

**Comment by gmontard** [comment]
Message LGTM

Though, don't you always have a default branch set with Git? And if not, is there a particular reason or a git command to use to make it so that we can advise the user to look into also? The env variable here sounds a bit hackish to me, especially if you're supposed to have a default branch setup.

**Comment by cfabianski** [comment]
`origin/HEAD` is always defined if you successfully cloned the repository.
You can end up with a missing `origin/HEAD` if you initialize a repo locally but didn't push it anywhere. That would explain it. In any cases, I will update the log level to make the message available directly without having to use --debug mode.
