### ISSUE TITLE
Flag to fail only on certain severity levels

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#1200]
We have a flag to only show findings on certain severity levels (--severity), as well as a flag to change the overall status code (--exit-code). Though, it's not possible to perform a full scan, report all the findings, but only fail a CI/CD pipeline on a certain level of severity. 

I propose we introduce a new flag called ```--fail-on-severity```, for e.g:
```bearer scan --fail-on-severity critical```

Expected behavior:
- Run every rules
- Report every finding
- Report an error status code only if "critical" findings are found.

Possible conflicts:
- What happens if the flag --exit-code is also used? It should take full precedence over the final exit status code
- What happens if the flag --severity is also used? It should also be applied.

**Comment by oneslash** [comment]
I cannot find `--severity` flag in the list of the `ScanFlagGroup` struct. Is it planned or somewhere else?

**Comment by gotbadger** [comment]
@oneslash its on report flags
```
Report Flags
  -f, --format string     Specify report format (json, yaml, sarif, gitlab-sast, rdjson, html)
      --output string     Specify the output path for the report.
      --report string     Specify the type of report (security, privacy, dataflow). (default "security")
      --severity string   Specify which severities are included in the report. (default "critical,high,medium,low,warning")
```
