### ISSUE TITLE
only support macOS 12+?

### ISSUE THREAD

**Issue by claviering** [Bearer/bearer#1247]
## Description & Reproduction

when i use bearer. there is: dyld: Symbol not found: _kIOMainPortDefault

`brew install bearer/tap/bearer`

`bearer scan my-repo`

## Expected Behavior

A progress bar will display the status of the scan.

## Actual Behavior

```
dyld: Symbol not found: _kIOMainPortDefault
Referenced from: /opt/homebrew/bin/bearer (which was built for Mac OS X 12.0)
Expected in: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
```

## Your Environment

- Operating System and version: macOS Big Sur 11.6 Chip Apple M1
- Output of 'bearer version':
```
bearer version: 1.22.0
```

**Comment by cfabianski** [comment]
Thanks for your report @claviering 
We use `macos-latest` to build and that's what causing it to drop the support for Big Sur. Easiest way to fix it would be to specify `macos-11` instead.

**Comment by claviering** [comment]
thx

**Comment by gotbadger** [comment]
@claviering we will likely include this change in the next release which should be next week. 

As a workaround you can use the docker method to run bearer if you dont want to wait: https://docs.bearer.com/reference/installation/#docker

**Comment by gotbadger** [comment]
It seems our build setup cant support macOS 11, we need to update the docs to make a note of this.

**Comment by claviering** [comment]
thanks, I use the docker method to run bearer

**Comment by gotbadger** [comment]
Going to close this issue off. We could limit the download from [brew](url) in [goreleaser.yaml](https://github.com/Bearer/bearer/blob/main/.goreleaser.yaml#L12) using `dependencies` but from searching goreleaser configs on github it dosen't seem like this is a very popular option so will leave it with just the readme change.
