### ISSUE TITLE
All reports add "Cached data used (no code changes detected). Unexpected? Use --force to force a re-scan."

### ISSUE THREAD

**Issue by moensch** [Bearer/bearer#1278]
## Description & Reproduction

This is a bug introduced in v1.23.0 (not present in v1.22.0)

* Run bearer v1.23.0 and write a report to a file `--output foo.html --report security --format html`
* Run the report a second time to ensure cache is used
* Inspect last line of report

Last line says:
```
Cached data used (no code changes detected). Unexpected? Use --force to force a re-scan.
```

This affects all report types and formats (tested with html, json, sarif).

## Expected Behavior

This line should not be printed into the report, but only to STDERR.

Essential

## Actual Behavior

Warning message is printed into the report filename.

## Your Environment

Running `bearer/bearer:v1.23.0` docker image.

**Comment by moensch** [comment]
I am reasonably certain this was introduced in #1255

**Comment by gotbadger** [comment]
Thanks for the report I will prepare a release shortly
