### ISSUE TITLE
Allow maximum scan time to be specified

### ISSUE THREAD

**Issue by didroe** [Bearer/bearer#1341]
We currently fix the maximum scan time for a file at 30 seconds. It would be good if users could configure the timeout, to allow bigger files to be scanned when needed.

**Comment by cfabianski** [comment]
I don't think that's a good idea to customise this limit. 
Disabling the rule `javascript_express_static_asset_with_session` is the best solution for now. Increasing the time would also require the memory to be bumped.
I would rather focus on making the rule less prone to timeout.
