### ISSUE TITLE
Using LSP to get usages of the method of function to do checks

### ISSUE THREAD

**Issue by oneslash** [Bearer/bearer#1414]
Hi everyone,

I was thinking about, if it would be a good idea to use LSPs to get usages of methods or functions and do checks there to make sure if they are being used right way. Like parameters are sanitized before.

**Comment by cfabianski** [comment]
Hi @oneslash 👋  

That's a good suggestion and actually it's been mentioned as part of the work regarding the next steps of the engine. 
This includes support for inter-procedural analysis or cross files. We've been looking at LSPs as part of that but we don't think they're suited to our needs. We need more information than they are able to provide, and we're not sure if we could integrate them into our engine without efficiency issues.
