### ISSUE TITLE
not finding/scanning all files

### ISSUE THREAD

**Issue by vlinder** [Bearer/bearer#1426]
## Description & Reproduction

Running the command below does not seem to scan all our files. Only around 15% seem to be scanned.

```shell
docker run --rm -v .:/tmp/scan bearer/bearer:latest scan /tmp/scan
```

## Expected Behavior

I would expect it to scan all files?

This is our number of actual js/ts source files.

```shell
$ git ls-files | grep -E '\.[tj]sx?$' | wc -l
    3222
```

## Actual Behavior

This is what we get:

```
Security Report

=====================================

Rules:
https://docs.bearer.com/reference/rules [v0.23.1]

Language    Default Rules  Custom Rules  Files
JavaScript  72             0             497

...
```

We get the same low number when we use the github action.

## Your Environment

- Operating System and version: docker on macOS
- Output of 'bearer version':
```
bearer version 1.32.0, build 12a566e5b53915f034631d02a4997e68dcff05f8
```

**Comment by cfabianski** [comment]
Thanks @vlinder. I have some good news. It appears that it's only a display issue so the scan actually takes all the files JSX, TSX, ... into account.
I will work on a fix for this 🐻
