### ISSUE TITLE
CWE-798 (javascript_lang_hardcoded_secret) does not match on conditional assingment

### ISSUE THREAD

**Issue by aramcheck** [Bearer/bearer#1454]
## Description & Reproduction

While testing bearer on multiple code repositories we accidentally found a code-fragment that was not properly flagged as a CWE-798:

```typescript
export const providers: Array<ServiceProviderInfo & { config: LLMProviderConfig }> = [
...
  {
    id: 'openai-gpt-3.5-turbo',
    description: 'OpenAI GPT-3.5 Turbo',
    config: {
      apiKey: '<hard-coded-secret that was left accidentally in the code>' || Settings.openAI.apiKey,
      baseUrl: Settings.openAI.baseUrl,
      model: 'gpt-3.5-turbo',
      system: DEFAULT_SYSTEM_PROMPT
    }
  }
...
];
```

## Expected Behavior

**HIGH: Hardcoded secret detected [CWE-798]**

## Actual Behavior

**N checks were run and no failures were detected. Great job! 👏**

## Possible Fix

A pattern could be added. Although other similar situations might by-pass the existing patterns.

## Your Environment

- Operating System and version: MacOS Ventura 13.1
- Output of 'bearer version' (Using Docker):

```
bearer version 1.33.1, build bc8261814122eb2af11e44d4faafd5ef1537f457
```

**Comment by gotbadger** [comment]
Thanks for the report @aramcheck we'll take a look
