### ISSUE TITLE
Repo access unavailable

### ISSUE THREAD

**Issue by orangel-h** [Bearer/bearer#1487]
## Description & Reproduction

When update using apt, access to repo https://apt.fury.io/bearer/ is unavailable

## Your Environment

- Operating System and version: WSL (Ubuntu 22.04)
- Linux kvz-oh 4.4.0-19041-Microsoft #3636-Microsoft Thu Oct 19 17:41:00 PST 2023 x86_64 x86_64 x86_64 GNU/Linux
- Output of 'bearer version':
```
bearer version: 1.37.0, build 5fd994cf0cb2003d167973bc5c72476faa4103b7
sha: xxx
```

**Comment by gotbadger** [comment]
Strange - thanks for the report we will take a look

**Comment by cfabianski** [comment]
Hey @orangel-h 

I just tried this

```bash
RUN echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" > /etc/apt/sources.list.d/fury.list
RUN apt-get update && apt-get install -y bearer=1.35.0
RUN apt-get upgrade bearer -y

CMD ["bearer", "version"]
```

And I get the following result

```bash
bearer version 1.37.0
```

Which means that everything went as expected.

Could you be more explicit about the issue you are facing please?

Thanks

**Comment by orangel-h** [comment]
Sorry @cfabianski but I did it and still have not access...

Cat for file:
➜  ~ cat /etc/apt/sources.list.d/fury.list
deb [trusted=yes] https://apt.fury.io/bearer/ /   

When I try "sudo apt update" I get:
...
Get:10 https://apt.fury.io/bearer  Packages
Err:11 https://apt.fury.io/bearer  Translation-en
  404  Not Found [IP: 54.204.238.15 443]
Err:11 https://apt.fury.io/bearer  Translation-en
  404  Not Found [IP: 54.204.238.15 443]
Err:11 https://apt.fury.io/bearer  Translation-en
  404  Not Found [IP: 54.204.238.15 443]
Err:11 https://apt.fury.io/bearer  Translation-en
  404  Not Found [IP: 54.204.238.15 443]
Err:11 https://apt.fury.io/bearer  Translation-en
  404  Not Found [IP: 54.204.238.15 443]
Ign:11 https://apt.fury.io/bearer  Translation-en
...

Also when a try wget on that URL I get:
➜  ~ wget https://apt.fury.io/bearer/
--2024-02-07 17:32:22--  https://apt.fury.io/bearer/
Resolving apt.fury.io (apt.fury.io)... 75.101.184.39, 54.209.91.188, 54.221.251.148, ...
Connecting to apt.fury.io (apt.fury.io)|75.101.184.39|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-07 17:32:23 ERROR 404: Not Found.

And, also when I try accessing inside a browser:
![image](https://github.com/Bearer/bearer/assets/25103500/3a7d0a88-0bf5-460d-a8fa-28ab49ebe1b3)


I don't know but I think the redirection is not working properly 🤷‍♂️

**Comment by gotbadger** [comment]
It seems our test actions on github dont have this issue but booting a docker container locally I get the same issue. Ive contacted gemfury who we use to host our apt packages to see if they can resolve the issue.

We do publish the debs as part of our releases which can be installed manually as a work around untill this is resolved.

**Comment by gotbadger** [comment]
I've not heard back from gemfury but even if you cant reach the package using https://apt.fury.io/bearer it seems possible to install now using the instructions here https://docs.bearer.com/reference/installation/#debian%2Fubuntu

See log: https://gist.github.com/gotbadger/a8f1caa262203c0d2945c7685547cbcd

If its stil an issue I would stick to using the deb files from the releases or use the install script.

**Comment by gotbadger** [comment]
I've not heard back from gemfury but even if you cant reach the package using https://apt.fury.io/bearer it seems possible to install now using the instructions here https://docs.bearer.com/reference/installation/#debian%2Fubuntu

See log: https://gist.github.com/gotbadger/a8f1caa262203c0d2945c7685547cbcd

If its stil an issue I would stick to using the deb files from the releases or use the install script.
