### ISSUE TITLE
Broken reference link in scan results

### ISSUE THREAD

**Issue by aryanxk02** [Bearer/bearer#1515]
## Description & Reproduction
I am going through the Quickstart guide present in the documentation. I noticed that the link provided in the scan report: https://docs.bearer.com/reference/rules/javascript_lang_logger_leak is not working. 

- Follow the guide: https://docs.bearer.com/quickstart/ for reproduction.

As shown in the terminal, the link: https://docs.bearer.com/reference/rules/javascript_lang_logger_leak leads to Page not found (404) error. 

## Expected Behavior

The correct link should be the one mentioned in the documentation: https://docs.bearer.com/reference/rules/javascript_lang_logger/

## Actual Behavior

1. Link
<img width="727" alt="image" src="https://github.com/Bearer/bearer/assets/59761275/da4065f1-32ec-4d8f-a3af-ef5259335db4">

2. Result
<img width="1074" alt="image" src="https://github.com/Bearer/bearer/assets/59761275/fb325719-1891-4459-b9e6-0ece3c7cc75f">

## Possible Fix

Update the link to https://docs.bearer.com/reference/rules/javascript_lang_logger/

## Your Environment

- Operating System and version: Mac OS Sonoma 14.x
- Output of 'bearer version': 
```
bearer version: 1.39.0
sha: xxx
```

**Comment by gotbadger** [comment]
This is a new rule and looks like the documentation wasnt rebuilt after the most recent rule release last week. Thanks for the report and is now fixed :)
