### ISSUE TITLE
Failed to get git context: couldn't parse origin url

### ISSUE THREAD

**Issue by krishanshamod** [Bearer/bearer#1519]
## Description & Reproduction

Getting the following error when scanning a GitHub repo which is cloned using SSH. 
`Error: failed to get git context: couldn't parse origin url: <SSHConfigHostName>:<GithubUsername>/<RepoName>.git`
(I have omitted sensitive information such as the SSH config host name, GitHub username, and repository name)

Command: `bearer scan .`

## Expected Behavior

It should do the scan

## Actual Behavior

```
Analyzing codebase
⠋  (9002/-) [0s] 
Error: failed to get git context: couldn't parse origin url: <SSHConfigHostName>:<GithubUsername>/<RepoName>.git
```

## Your Environment

- Operating System and version: `Ubuntu 22.04.3 LTS`
- Output of 'bearer version':  `bearer version 1.39.0, build 1f0448825fb4ec6be72b07616e890f92835b952e`

**Comment by gotbadger** [comment]
@krishanshamod could you let us know the output of `git --version`

**Comment by krishanshamod** [comment]
Hi @gotbadger it's `git version 2.43.0`

**Comment by gotbadger** [comment]
@krishanshamod git version looks ok. This is a bit weird as we often scan github projects without issues. 

Couple of questions:
- Are you able to provide the repo name? If not do you have a SSHConfigHostName diffrent to `git@github.com` ? 
- Is there anything unusual about the name? 
- Do you have this issue with other repos from github maybe you could try cloning https://github.com/Bearer/WebGoat and see if you have the same issue?

**Comment by krishanshamod** [comment]
@gotbadger Here's the SSH config I use.

```
Host github
  Hostname github.com
  User git
  IdentityFile ~/.ssh/privatekey
```

That SSH private key is secured using a passphrase. Maybe that's the issue.

**Comment by gotbadger** [comment]
Password should be fine I think but is the host setup as `github` instead of `github.com`? - does the error looks like this?

```
Error: failed to get git context: couldn't parse origin url: git@github:krishanshamod/repo.git
```

Its quite hard to help unless you post the error so we can write a test for it. Is there some sensitive string in the origin url?

**Comment by gotbadger** [comment]
Im going to close this reopen if you have some more info but realistically using custom hostname for github isn't something we will support. If you want to see how the parsing works see here: https://github.com/Bearer/go-vcsurl/blob/allow-parsing-of-devops-azure-urls/vcsurl_test.go

**Comment by krishanshamod** [comment]
Hi @gotbadger, sorry for the late response. The error looks like this
`Error: failed to get git context: couldn't parse origin url: github:krishanshamod/repo.git`

Host is `github` because my SSH Config host is `github`

```
Host github
  Hostname github.com
  User git
  IdentityFile ~/.ssh/privatekey
```

Also, this SSH private key is protected with a passphrase.
