### ISSUE TITLE
Add references and guides to html scan output

### ISSUE THREAD

**Issue by aryanxk02** [Bearer/bearer#1520]
## Description & Reproduction
I was running the `bearer scan . --scanner secrets` command and realised that there are no links for reference rules (https://docs.bearer.com/reference/rules), community discord and documentation guides(https://docs.bearer.com/guides/bearer-cloud/) present in the html output as in case of terminal output. I'd like to know if there is a need to add these links to maintain uniformity all over the output results. 

## Expected Behavior
References to be present in the HTML output results to maintain uniformity over scan results. 
- https://docs.bearer.com/reference/rules [v0.28.0]
- Need help or want to discuss the output? Join the Community https://discord.gg/eaHZBJUXRF
- Retain state and manage your findings directly on Bearer Cloud. Learn more at https://docs.bearer.com/guides/bearer-cloud/

## Actual Behavior

<img width="697" alt="image" src="https://github.com/Bearer/bearer/assets/59761275/976210db-16a6-4884-b399-2bebe139f03e">

## Possible Fix

Update `secret_detection.yml` file with necessary changes.

## Your Environment

- Operating System and version: macOS Sonoma, 14.x
- Output of 'bearer version': 1.39.0

**Comment by gotbadger** [comment]
The HTML output does not link to the docs since the content is basically the same, the other links are not required in this report we just have those in the CLI output.

Gitleaks is actually missing from the docs and had no link to the docs so that will be updated and added in #1521
