### ISSUE TITLE
Can only scan git projects?

### ISSUE THREAD

**Issue by 7uup** [Bearer/bearer#1550]
<img width="445" alt="image" src="https://github.com/Bearer/bearer/assets/59676816/143d7c92-0c8f-4a4c-b748-8a2156b05163">

**Comment by gotbadger** [comment]
it should work without git possibly related to https://github.com/Bearer/bearer/issues/1553

**Comment by gotbadger** [comment]
@7uup feel freee to comment on https://github.com/Bearer/bearer/issues/1553#issuecomment-2045533547 if you can give some more info

**Comment by Re54ik** [comment]
**Force local C.UTF-8**

`LANG=C.UTF-8 bearer scan /path/to/the/project`
