### ISSUE TITLE
Inconsistent vulnerability findings due to fluctuating system resources

### ISSUE THREAD

**Issue by metekeltek** [Bearer/bearer#1562]
We discovered that using the bearer scanner in an environment with less computing power can lead to fewer findings by the scanner.

We ran bearer scan in debug mode and saw that the reason for this is the fixed File Timeout found in [this settings file](https://github.com/Bearer/bearer/blob/e267aa91d68a9e3e70890b03ded971b12c30d95f/internal/commands/process/settings/settings.go#L26C2-L26C20).

This can lead to vulnerabilities not being discovered by bearer if scanning a file with a vulnerability takes longer than 30 seconds.  
E.g. `2024-04-09 14:14:57 DBG error processing public/lib/prism.js: file processing time exceeded process=main `. Here prism.js could not be scanned by bearer in 30 seconds which led to 2 high findings not being discovered by the scanner.

I would suggest adding a flag `--file-timeout` (similar to `--domain-resolution-timeout`), where a custom file timeout can be set.

This way, even less powerful environments can unlock the full potential of bearer.

**Comment by cfabianski** [comment]
Thanks @metekeltek for the feedback.
I think it would be a matter of reverting this commit https://github.com/Bearer/bearer/pull/477 which has been done in an attempt to reduce the noise in the flags.

**Comment by kovacs-levent** [comment]
I agree that this would be useful.

I think in general, a tool should allow users to scan any file they want with the proper configuration and without having to modify the source code. Based on the PR you linked @cfabianski, file-size-max and timeout also got hardcoded. This would mean that a user has no option to scan a large file, only by changing the hardcoded values in the source code. While I agree, the size is pretty large, in extreme cases, these large files are missed. This could be especially problematic with legacy codebases, it could happen that there are larger code files than 2MB are kept around in a repository.

Let users decide if they want to scan these large files as well by giving this as an option. So I'd suggest to not have any controls in place without configuration options which in extreme cases would block the tool from scanning some file.

**Comment by undergroundwebdesigns** [comment]
I also think #477 should be reverted. I'm in the process of rolling out bearer as a security tool at my workplace, and it's disconcerting to say the least to discover that it can skip security findings with just a debug message due to resource constraints, especially when there's no way to configure it otherwise or increase the timeout / memory limit / etc. Ideally those options would be configurable, but I also think the scan should log a finding if the scan is aborted due to resource constraints so that at least the user knows the scan could not be completed and some findings may not have been detected.

**Comment by cfabianski** [comment]
I have made [`errors` part of the jsonv2](https://github.com/Bearer/bearer/pull/1705) output which will solve that issue.
