### ISSUE TITLE
No rules found after installing with brew

### ISSUE THREAD

**Issue by siewer** [Bearer/bearer#1654]
## Description & Reproduction
What I did so far:
```
brew install bearer/tap/bearer
cd java-app
bearer scan . --scanner=sast
```

## Expected Behavior

I expect output related with scan started and information that there is a problem or no problems

## Actual Behavior

Output related with information that there are no rules found matching code that is in `java-app` directory - this is maven java spring project which should be covered according to the docs

```
bearer scan . --scanner=sast
Analyzing codebase
⠇  (392653/-) [0s]
Loading rules
Scanning target .
 └ 100% [===============] (6938/6938) [22s]
Running Detectors
Generating dataflow
Evaluating rules


Security Report

=====================================

Zero rules found. A security report requires rules to function. Please check configuration.

Error: report error: 0 rules found for supported language, default rules could not be downloaded or possibly disabled without using --external-rule-dir
```

## Your Environment

- Operating System and version: macOS Sonoma 14.5
- Output of 'bearer version':
```
bearer version 1.45.2, build a179682b80de1ac0004ee6d217dae18cd081f40c
```

**Comment by siewer** [comment]
I have created this issue a little too fast but docs are not clear ;)
After cloning bearer-rules and settings --external-rules-dir it works like a charm

**Comment by gotbadger** [comment]
@siewer the rules should download automatically so you should not be required to clone the rules repo. There maybe some issue that preventend downloading if you use --debug should get some more info.
