### ISSUE TITLE
Ignored git folders/file are scanned while it shouldn't

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#280]
Folders/file present /gitignore are scanned.

## Description

Folders and files referenced in a .gitignore shouldn't be scanned.

## Expected Behavior

Avoid scanning files and folder present in a .gitignore

## Steps to Reproduce

1. Add a folder/file `folder_to_ignore/test.txt` in a sample app and add `folder_to_ignore` folder in the app .gitignore
2. Scan the sample app in debug mode .
3. Notice that it scan the files present in the `folder_to_ignore` folder.

## Context

It slows down the scan a lot.

## Your Environment

- Version used: 0.19.0
- Target codebase stack (e.g. Ruby): Ruby
- Operating System and version: Mac OS 13
- Link to your project or code sample: n/a

**Comment by cfabianski** [comment]
They should already be ignored https://github.com/Bearer/curio/blob/6aa6f39169ed0a7684e86dfc3dd6249d5b7b0512/pkg/util/file/file.go#L75 with this `fileInfo.isGitIgnored`

https://github.com/Bearer/curio/blob/fa16564adaea69ab8b8f658dc83bce6f793be150/pkg/util/file/file.go#L213-L216

**Comment by spdawson** [comment]
I haven't been able to reproduce this locally. @gmontard Could you share the exact entry that you are adding to the `.gitignore` file, and what you see in the output that indicates the scanning of files that ought to be ignored?

**Comment by gmontard** [comment]
For instance I have in my .gitignore
```/storage/*```

And when I scan in debug mode you can see that it goes in each file of this directory still:
```
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/eg/89/eg89qvwge5q7w5fo8azmv3ax1e7l"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/ei/8a/ei8abryomzelyy7o5p5wyt0xy2us"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/eo/29/eo29uck46rdzqvoebyidyckqlfc7"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/eo/3b/eo3bvriwbq6e2szoi9klzfcw2zgl"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/eo/j1/eoj1pd5imqf38pbtupdl4cl77kgo"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/ep/ez/epezmfevghkmdxlsosv0epnr5joo"}
{"level":"debug","time":"2022-12-19T15:20:03Z","message":"ignored due to file type /Users/guillaume/Documents/woody3/storage/eq/0r/eq0r35t1d8f68ezkyxdfb67jbyqv"}
```

**Comment by cfabianski** [comment]
The content of the .git folder also gets scanned :-(
