### ISSUE TITLE
Can't execute Curio on Ubuntu 22.10 without sudo permission

### ISSUE THREAD

**Issue by b1pb1p** [Bearer/bearer#294]
## Description

Curio seems unable to create the json file at begining of scan without sudo permissions on Ubuntu 22.10. 

## Expected Behavior

Curio should be able to scan without super user permissions.

## Actual Behavior

Works only with super user permissions .

```
ubuntu@d2-8-sbg5:~$ ./bin/curio scan bear-publishing/
{"level":"error","time":"2022-12-19T07:20:10Z","message":"failed to create path /tmpe566c0f8c7ffb00cb50b8bc7fa842e58801f054d-b1bbbdcccc1cda1137e82d75f34a6e7d8b134707.jsonl, open /tmpe566c0f8c7ffb00cb50b8bc7fa842e58801f054d-b1bbbdcccc1cda1137e82d75f34a6e7d8b134707.jsonl: permission denied, (*os.File)(nil)"}
Scanning target bear-publishing/
Error: filesystem scan error: open /tmpe566c0f8c7ffb00cb50b8bc7fa842e58801f054d-b1bbbdcccc1cda1137e82d75f34a6e7d8b134707.jsonl: permission denied
```

```
ubuntu@d2-8-sbg5:~$ sudo ./bin/curio scan bear-publishing/
Scanning target bear-publishing/
 └  26% [==>            ] (47/177, 28 files/s) [1s:4s]^C
```

## Possible Fix

Maybe a yml path issue ? 

## Steps to Reproduce

1. Install curio with the script on Ubuntu 22.10
2. try to scan a repo in current user home
3. see it fail
4. retry with sudo

## Your Environment

- Version used: v0.19
- Target codebase stack (e.g. Ruby): ruby
- Operating System and version: Ubuntu 22.10
- Link to your project or code sample: https://github.com/Bearer/bear-publishing

**Comment by b1pb1p** [comment]
@spdawson thinks this should be fixed by https://github.com/Bearer/curio/pull/271

**Comment by b1pb1p** [comment]
Same issue on Fedora 36.

**Comment by cfabianski** [comment]
Fixed by https://github.com/Bearer/curio/pull/271
