### ISSUE TITLE
`--only-policy` option doesn't check policy existence

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#334]
## Description

Running `--only-policy` (or  `--skip-policy`) doesn't check if the policy IDs exist, leading to bad UX and misleading output.

## Expected Behavior

Throw an error if using a policy ID that doesn't exist

## Actual Behavior

Fail silently

## Possible Fix

Check if policy IDs exist first

## Steps to Reproduce

1. `curio scan . --only-policy CR-000`
2. `curio scan . --skip-policy CR-000`

## Your Environment

- Version used: 0.21.1
- Target codebase stack (e.g. Ruby): Ruby
- Operating System and version: Mac

**Comment by cfabianski** [comment]
This also applies to detectors (check the detector exists)
