### ISSUE TITLE
Revisit structure for detectors/policies

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#336]
## Description

Curio works with detectors and policies. Detectors are there to enrich the dataflow report, policies are there to look at the dataflow report and apply policies based on the output.

For example:
- a detector would be located in `/pkg/commands/process/settings/custom_detectors/` (e.g. `/pkg/commands/process/settings/custom_detectors/ruby_loggers.yml`)
- a policy would be located in `pkg/commands/process/settings/policies/` (e.g. `/pkg/commands/process/settings/policies/leakage.rego` and an entry inside `/pkg/commands/process/settings/policies.yml`)

Whenever we implement a new detection, we either rely on an existing policy (e.g. leakage applies to both cookies and session), either we enrich the collection of policies.

It might be a bit difficult for a new comer to know where to start especially as we introduce the remediation layer on top.

## Proposal

We could have a structure like this

```bash
/policies/ruby/shared/shared.rego
/policies/ruby/CR-001/detectors/loggers.yml
/policies/ruby/CR-001/leakage.rego
/policies/ruby/CR-001/rule.yml
/policies/ruby/CR-001/README.md
```

We could end up repeating the policies (like `leakage.rego` would be similar for both session and cookies) but that would definitely help any new comer to understand where to start and to contribute.

**Comment by markmichon** [comment]
Does it make more sense to group by policy rather than language? so `policies/CR-001/shared`, `policies/CR-001/ruby/...`, etc.

 For example: if my multi-language project is leaking data to a logger (CR-001) in both ruby and js, the core rationale behind why this is a problem is shared by the policy. Only the implementation details differ by language.

**Comment by cfabianski** [comment]
> Only the implementation details differ by language.

The remediation would also be a little bit different. 

I'll spike this one up though and I will see what we end up with
