### ISSUE TITLE
Battle tests on Top 5k Ruby Projects and review policy results

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#353]
We have the [battle tests](https://github.com/Bearer/curio/tree/main/battle_tests) that we used to check the stats on the top 5k repositories per language.
It is being triggered by this [workflow](https://github.com/Bearer/curio/blob/main/.github/workflows/battle_tests.yml)

Now that we have the policies in place, we would like to update the battle tests a bit to allow it to run the policies and to send the output of the policies on S3 (so that we can review the results).

NB: This means only run it on the Ruby projects only

**Comment by spdawson** [comment]
@cfabianski It looks like the existing battle test runner is generating a `stats` report. Do we want to retain this alongside the `policies` report?

Also, do we have an existing S3 bucket that is suitable for this data? Or should we create a new one?

**Comment by cfabianski** [comment]
> @cfabianski It looks like the existing battle test runner is generating a `stats` report. Do we want to retain this alongside the `policies` report?

If we can keep both, that would be great.
The battle tests is using the binary but maybe we could use the linux package (now that we are building it)

> Also, do we have an existing S3 bucket that is suitable for this data? Or should we create a new one?

We don't, it's preferable to create a new one, let me know once you are there so that I can assist.
