### ISSUE TITLE
Non-supported language policy output suggests non-working command

### ISSUE THREAD

**Issue by markmichon** [Bearer/bearer#385]
When running policy scan on a project that doesn't support policy scans (JS), curio presents an incorrect command for running a dataflow scan.

## Description

The final line of the output provides incorrect instructions

```
curio scan .
Scanning target .
 └ 100% [===============] (984/984, 56 files/s) [17s]
Running Detectors
Generating dataflow

The policy report is not yet available for your stack. Learn more at https://curio.sh/explanations/reports/

Though this doesn’t mean the curious bear comes empty-handed, it found:

- 13 unique data type(s), representing 66 occurrences, including PII, Personal Data (Sensitive).
- 2 database(s) storing 13 data type(s) including 0 encrypted data type(s).
- 3 external service(s).

Run the data flow report if you want the full output using: curio scan --report dataflow
```

## Expected Behavior

`curio scan --report dataflow [PATH]`

## Actual Behavior

`curio scan --report data flow`

## Your Environment

- Version used: 0.21.1
- Target codebase stack (e.g. Ruby): javascript
- Operating System and version:
- Link to your project or code sample:

**Comment by markmichon** [comment]
Apparently this is fixed, but a release hasn't been made yet.

**Comment by cfabianski** [comment]
Duplicate of https://github.com/Bearer/curio/issues/371
