### ISSUE TITLE
No file for symlink causes curio to error

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#388]
## Description
Curio errors when processing symlink that does not exist in the project

## Expected Behavior

The file is skipped

## Actual Behavior

```
./curio scan  ~/development/mastodon/
Error: filesystem scan error: stat /Users/gotbadger/development/mastodon//public/500.html: no such file or directory
filesystem scan error: stat /Users/gotbadger/development/mastodon//public/500.html: no such file or directory
```

## Steps to Reproduce

1. clone https://github.com/mstdn/Mastodon
2. run curio scan

## Context

Looks like https://github.com/mstdn/Mastodon/blob/main/public/500.html points to a file that does not exist initally in the project.

## Your Environment

- Version used:  0.21.1
- Target codebase stack (e.g. Ruby): Ruby
- Operating System and version: Darwin
- Link to your project or code sample: https://github.com/mstdn/Mastodon

**Comment by cfabianski** [comment]
It should be skipped here https://github.com/Bearer/curio/blob/bdaf5fd2f4fbcb2258d04ecc441574e8b810af7d/pkg/commands/process/balancer/fileignore/fileignore.go#L38-L42
