### ISSUE TITLE
Performance test new detectors

### ISSUE THREAD

**Issue by vjerci** [Bearer/bearer#402]
Due to internal workings of new detectors (running detector for each node, and its children) we might be seriously degrading scan performance O(n x n x n).
It might be good to stay on a safe side by doing early performance/battle test to have some benchmarks and provide ensurance that we haven't degraded performance.

**Comment by cfabianski** [comment]
We are 2 times slower compared to main.

**Comment by cfabianski** [comment]
We are now back to comparable times to what we had before. Closing
