### ISSUE TITLE
False positive on CR-025 (Secrets Leak)

### ISSUE THREAD

**Issue by b1pb1p** [Bearer/bearer#423]
False positive : policy failed on default credentials. 

CRITICAL: Do not leak secrets. [CR-025]
https://curio.sh/reference/policies/#CR-025

For the following line:
```
# DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
```

This line was autogenerated and is commented out in the code. I see this being an issue if a real password was used in the commented-out line. 

--> Should treat differently or discard default credentials detected by CR-025

- Version used: v0.22
- Target codebase stack (e.g. Ruby): Ruby

**Comment by cfabianski** [comment]
Duplicates https://github.com/Bearer/curio/issues/438
