### ISSUE TITLE
Cache not tracking files states in non git directory

### ISSUE THREAD

**Issue by vjerci** [Bearer/bearer#433]
## Description

When you have an empty non-git directory and create 2 files in it. eg. users.rb containing `logger.info(user.email)`, and admins.rb containing `logger.info(user.name)`
Then run a scan, after it delete the `users.rb` and rerun the scan.
Scan will load from cache and think `users.rb` still exists in that directory.

## Expected Behavior

Re-running the scan after file deletion should detect changes instead of loading from cache.

## Actual Behavior

Scan will load from cache and think `users.rb` still exists in that directory.

## Possible Fix

If there is no git directory we shouldn't cache the scan

## Steps to Reproduce

1. Create users.rb file containg `logger.info(user.email)`
2. Create admins.rb containing `logger.info(user.name)`
3. Run the scan without force
4. Delete  users.rb
5. Rerun the scan without force

**Comment by cfabianski** [comment]
Not a big issue for now and very edge case-y. Main use case being you scan the repo you are cloning in a CI or similar
