### ISSUE TITLE
Links to Curio's policy reference are dead in Policy report.

### ISSUE THREAD

**Issue by Ombe-b** [Bearer/bearer#484]
## Description

I ran Curio against bear-publishing test app with curio v0.22 ; the provided links to a policy are dead :

https://curio.sh/reference/policies/#CR-004

## Expected Behavior

It seems the policies are now rules, and are hosted in the documentation here : https://curio.sh/reference/rules/

- Version used: v0.22
- Target codebase stack (e.g. Ruby): Ruby
- Operating System and version: MacOS
- Link to your project or code sample: bear-publishing

**Comment by gotbadger** [comment]
The documentation site is currenly ahead of the latest release (which we are testing right now). Going to @markmichon and @cfabianski about how we want to manage this but going to close this issue for now as its expected older versions might have dead links in some cases

**Comment by markmichon** [comment]
Closing this as the issue isn't related to the links. Will create new issue when a decision on releases has been made.

**Comment by gotbadger** [comment]
Documentation has been updated to reflect the current release
