### ISSUE TITLE
Write JS Rules

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#504]
- [x] Loggers @vjerci 
- [x] Cookies @vjerci 
- [x] Session @vjerci 
- [x] File Generation @cfabianski https://github.com/Bearer/curio/pull/546
- [x] Sentry @cfabianski https://github.com/Bearer/curio/pull/526
- [x] Exception @cfabianski https://github.com/Bearer/curio/pull/540
- [x] Weak Encryption @vjerci 
- [ ] SSL Verification @vjerci (I believe this one isn't feasible to do) 
- [x] JWT @vjerci https://github.com/Bearer/curio/pull/549
- [x] HTTP Get/Post @vjerci https://github.com/Bearer/curio/pull/551
- [x] Google Analytics @vjerci 
     - [x] Google tag manager @vjerci https://github.com/Bearer/curio/pull/554
     - [x] Google analytics frontend (without gtm) @vjerci  https://github.com/Bearer/curio/pull/566
     - [x] Google Analytics react library @vjerci  https://github.com/Bearer/curio/pull/567
- [x] Algolia (1,131K weekly downloads on NPM) @elsapet 
    - https://www.algolia.com/doc/api-client/getting-started/install/javascript/?client=javascript
    - https://www.npmjs.com/package/algoliasearch
- [x] Elasticsearch (771K weekly downloads on NPM) @vjerci https://github.com/Bearer/curio/pull/580
     - https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html
     - https://www.npmjs.com/package/@elastic/elasticsearch
- [x] Datadog   @vjerci 
  - [x] hot shots 1.5M weekly downloads @vjerci  https://github.com/Bearer/curio/pull/576
  https://www.npmjs.com/package/hot-shots
  - [x] Browser RUM integration (1 M weekly downloads) @vjerci https://github.com/Bearer/curio/pull/581
     - https://docs.datadoghq.com/integrations/rum_javascript/#pagetitle
     - https://www.npmjs.com/package/@datadog/browser-rum
  - [Data receiving only - not relevant] Typescript API(300K weekly downloads) @vjerci this one is for getting data
     - https://docs.datadoghq.com/api/latest/?code-lang=typescript
     - https://www.npmjs.com/package/@datadog/datadog-api-client
- [x] NewRelic (785K weekly downloads on NPM) @elsapet 
  - https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs/
  - https://www.npmjs.com/package/newrelic
- [x] Segment @elsapet 
    - [x] Analytics-node (708K weekly downloads)
         - https://www.npmjs.com/package/analytics-node
    - [x] Analytics.js (259K weekly downloads on NPM) 
    - Note: for Analytics.js we are not yet handling snippets e.g. any JS within `<script>` tags
         - https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/
         - https://www.npmjs.com/package/@segment/analytics-next
- [x] Bugsnag (562K weekly downloads on NPM) @elsapet 
  - https://docs.bugsnag.com/platforms/javascript/
  - https://www.npmjs.com/package/@bugsnag/js
- [x] OpenTelemetry (multiple libs; highest 4,880K weekly downloads on NPM) @elsapet 
  - https://opentelemetry.io/docs/instrumentation/js/
  - Node
    - https://www.npmjs.com/package/@opentelemetry/api (4,880K weekly downloads)
    - https://opentelemetry.io/docs/instrumentation/js/getting-started/nodejs/
    - https://www.npmjs.com/package/@opentelemetry/sdk-node (366K weekly downloads)
  - Browser JS
    - Note: we are not handling snippets e.g. any JS within `<script>` tags
    - https://opentelemetry.io/docs/instrumentation/js/getting-started/browser/
    - Examples: https://github.com/open-telemetry/opentelemetry-js/tree/main/examples/opentelemetry-web
    - https://www.npmjs.com/package/@opentelemetry/sdk-trace-web (93K weekly downloads)
    - https://www.npmjs.com/package/@opentelemetry/instrumentation-document-load (36K weekly downloads)
- [x] Rollbar (479K weekly downloads on NPM) @vjerci https://github.com/Bearer/curio/pull/595
  - https://docs.rollbar.com/docs/javascript
  - https://www.npmjs.com/package/rollbar
  - [x] Browser JS 
    - https://docs.rollbar.com/docs/browser-js
  - [x] Node 
    - https://docs.rollbar.com/docs/nodejs
- [x] HoneyBadger (130K weekly downloads on NPM) @vjerci 
  - https://www.npmjs.com/package/@honeybadger-io/js
  - [x] Browser JS
    - https://docs.honeybadger.io/lib/javascript/integration/browser/
  - [x] Node
    - https://docs.honeybadger.io/lib/javascript/integration/node/
- [x] Airbrake (53K weekly downloads on NPM) @elsapet 
  - https://docs.airbrake.io/docs/platforms/javascript/
  - https://www.npmjs.com/package/@airbrake/browser

### [Analytics and logging libraries currently unsupported](#currently-unsupported-analytics-and-logging-libraries)
<details>

- Druid
  - https://druid.apache.org/docs/latest/development/javascript.html
  - Can’t find official lib on NPM; unofficial query libs < 5K weekly downloads

Analytics libraries we support for Ruby but that we won't support for JS yet: 

- InfluxDB
  - Node.js (44K weekly downloads on NPM)
    - https://docs.influxdata.com/influxdb/cloud/api-guide/client-libraries/nodejs/
    - https://github.com/influxdata/influxdb-client-js
    - https://www.npmjs.com/package/@influxdata/influxdb-client
  - JavaScript browser client (~2K weekly downloads on NPM)
    - https://docs.influxdata.com/influxdb/cloud/api-guide/client-libraries/browserjs/
    - https://www.npmjs.com/package/@influxdata/influxdb-client-browser
- ClickHouse JS (~8K weekly downloads on NPM)
     - https://clickhouse.com/docs/en/integrations/language-clients/nodejs/
- AWS Redshift (6K weekly downloads on NPM)
     - https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-redshift/index.html
     - https://www.npmjs.com/package/@aws-sdk/client-redshift
- Splunk (4k weekly downloads on NPM)
  - https://dev.splunk.com/enterprise/docs/devtools/javascript/sdk-javascript/
  - https://www.npmjs.com/package/splunk-sdk
- ScoutAPM (~2K weekly downloads on NPM)
  - https://scoutapm.com/docs/node
  - https://www.npmjs.com/package/@scout_apm/scout-apm
- Google Dataflow (1,200 weekly downloads on NPM)
     - https://cloud.google.com/nodejs/docs/reference/dataflow/latest

</details>

### Code Snippets Examples

<details> 

## Loggers

<details>

```javascript
const users = []

function generateUsername(firstname, surname) {
    return `${firstname[0]}-${surname}`.toLowerCase();
}

arr.forEach(element => {
	const username = generateUsername(user.firstname, user.surname);

	users.push({
		email: user.email,
		first_name: user.firstname,
		username
	})
});

console.log("user successfully connected", user.email);
console.table(users)

// Winston specific
const ctx = {
	{ 
		user: {
			email: "",
		}
	}
};

// catch the sensitive information from the context
logger.child({ context: ctx }).info('Order "1234" was processed successfully'); 

const childLogger = logger.child({ context: ctx });
childLogger.info('Order "1234" was processed successfully'); 

logger.log({
  level: 'info',
  message: 'user successfully connected' + user.email
});

// constructor function
function Person () {
    this.name = 'John',
    this.age = 23,
}

// create objects
const person1 = new Person();
const person2 = new Person();

// access properties
console.log(person1.name);  // John
console.log(person2.name);  // John
```

</details>

## Cookies

<details>

```javascript
const session = require('cookie-session')
const express = require('express')
const app = express()

app.use(session({
	...
  cookie: {
    secure: true, // Ensures the browser only sends the cookie over HTTPS.
    httpOnly: true, // Ensures the cookie is sent only over HTTP(S), not client JavaScript, helping to protect against cross-site scripting attacks.
    domain: 'example.com', // indicates the domain of the cookie; use it to compare against the domain of the server in which the URL is being requested. If they match, then check the path attribute next.
    path: 'foo/bar', // indicates the path of the cookie; use it to compare against the request path. If this and domain match, then send the cookie in the request.
    expires: expiryDate // use to set expiration date for persistent cookies.
  }
}))


// ...

const cookieConfig = {
  httpOnly: true, // to disable accessing cookie via client side js
  //secure: true, // to force https (if you use it)
  maxAge: 1000000, // ttl in seconds (remove this option and cookie will die when browser is closed)
  signed: true // if you use the secret with cookieParser
};
app.get('/set', (req, res) => {
  res.cookie('test', user.email, cookieConfig);
});
```

</details>

### Links

- https://expressjs.com/en/advanced/best-practice-security.html#use-cookies-securely

## File Generation

<details>

```javascript
fs.writeFile('<filename>', <content>, callback);
fs.appendFile('<filename>', <content>, callback);

//

const users = []

function generateUsername(firstname, surname) {
    return `${firstname[0]}-${surname}`.toLowerCase();
}

arr.forEach(element => {
	const username = generateUsername(user.firstname, user.surname);

	users.push({
		email: user.email,
		first_name: user.firstname,
		username
	})
});

const fs = require("fs");

fs.writeFile("data.csv", data, "utf-8", (err) => {
  if (err) console.log(err);
  else console.log("Data saved");
});
```

</details>

## Session / Local Storage

<details>

```javascript
localStorage.setItem("User email", user.email)
```

</details>

## Sentry

<details>

```javascript
Sentry.configureScope(scope => {
  scope.setExtra('email', user.email);
  scope.setTag('user_email', user.email);
  scope.setUser({ email: user.email });
  // scope.clear();
});

Sentry.addBreadcrumb({
  message: 'My Breadcrumb',
  // ...
});

Sentry.captureMessage('Hello, world!');
Sentry.captureException(new Error('Good bye'));
Sentry.captureEvent({
  message: 'Manual',
  stacktrace: [
    // ...
  ],
});
```

</details>

## Exceptions

<details>

```javascript
throw new CustomError(`Error with ${user.email}`)
throw `${user.email}`

reject('Error with user ' + user.email);

Promise.reject(new Error('fail' + user.email))
```

</details>

## Weak Encryption

<details>

```javascript
var crypto = require('crypto');

var key = 'secret key';
var encrypted = crypto.createHmac('sha1', key).update(user.password)
var hashmd5 = crypto.createHash('md5').update(user.password)

var encrypted = crypto.createHmac('sha1', key).update(password)
var hashmd5 = crypto.createHash('md5').update(password)

// Should use BCrypt or Scrypt for encrypting password
```

</details>

## SSL Verification

<details>

```javascript
const express = require('express')
const app = express()
const helmet = require('helmet')
app.use(helmet())

// import express from "express";
// import { express } from "express";
// const express = require('express')

// 
app.use(helmet.hsts()); // default configuration
app.use(helmet.hsts("<max-age>", "<includeSubdomains>")); // custom configuration
```

</details>

### Links

- https://expressjs.com/en/advanced/best-practice-security.html#use-tls

## JWT

<details>

```javascript
var jwt = require('jsonwebtoken');
var token = jwt.sign({ user: { email: 'bar' }}, 'shhhhh');

var token = jwt.sign({ foo: 'bar' }, privateKey, { algorithm: 'RS256' });
jwt.sign({ foo: 'bar' }, privateKey, { algorithm: 'RS256' }, function(err, token) {
  console.log(token);
});
```

</details>

### Links

- https://github.com/auth0/node-jsonwebtoken

### Detect Insecure URL + Insecure params 

- [axios](https://github.com/axios/axios)
- [node-fetch](https://github.com/node-fetch/node-fetch)

<details>

```javascript
import axios from 'axios';
//const axios = require('axios'); // legacy way
axios.get(`http://example.com/user?email=${user.email}`)
  .then(function (response) {
    // handle success
    console.log(response);
  });

axios.get('http://example.com/user', {
    params: {
      email: user.email
    }
  })
  .then(function (response) {
    console.log(response);
  });

const response = await axios.get('http://example.com/user?email=' + user.email);
```

```javascript
// GET request for remote image in node.js
axios({
  method: 'get',
  url: 'http://example.com',
})
  .then(function (response) {
    response.data.pipe(fs.createWriteStream('ada_lovelace.jpg'))
  });
```

```javascript
import fetch from 'node-fetch';

const response = await fetch('https://github.com/');
```

</details>

### Detect Insecure URL

<details>

```javascript
axios.post('http://example.com/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })
  .then(function (response) {
    console.log(response);
  })
```

```javascript
// Send a POST request
axios({
  method: 'post',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
});
```

```javascript
import fetch from 'node-fetch';

const user = { email:  "", gender: "" };

const response = await fetch('http://httpbin.org/post', {
	method: 'post',
	body: JSON.stringify(user),
	headers: {'Content-Type': 'application/json'}
```

```javascript
import fetch from 'node-fetch';
const params = new URLSearchParams();
params.append('email', user.email);

const response = await fetch('https://httpbin.org/post', {method: 'POST', body: params});
```

</details>

### Functions

<details>

```javascript
function getUserAccount() {
  return axios.get('/user/12345');
}
```

</details>

</details>

**Comment by elsapet** [comment]
Closing as all pertinent tasks have been completed.

Tasks listed that we are not handling now: 
* SSL Verification - this is not feasible to do
* Snippet support (e.g. `<script>` tags in HTML files) for logging/analytics library detection
* Less popular logging/analytics libraries, some of which we handle for Ruby
