### ISSUE TITLE
Documentation: Not able to install curio on Ubuntu with the instructions given 

### ISSUE THREAD

**Issue by bunufi** [Bearer/bearer#547]
Installation fails when following instructions found in the readme (https://github.com/Bearer/curio#debianubuntu) on Ubuntu. 

The following line
```
echo deb [trusted=yes] https://apt.fury.io/bearer/ / | sudo tee -a /etc/apt/sources.list.d/fury.list
```

results in 
![image](https://user-images.githubusercontent.com/12247686/218065639-5209bbd2-1686-4a86-86fd-3ebeedf920a5.png)

which leads to package not found when trying to install. 

As you can see from the screenshot, I am using `zsh` and it might be the reason why this fails. 

Hope that helps.

**Comment by gotbadger** [comment]
Thanks for the report will take a look

**Comment by gotbadger** [comment]
@bunufi looks like the command should have been:
```
echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" | sudo tee -a /etc/apt/sources.list.d/fury.list
```
We have updated the readme to reflect this. I'll let you close this issue if it fixes the problem.

**Comment by gotbadger** [comment]
closing as complete - no futher feedback from user

**Comment by bunufi** [comment]
Sorry, I forgot to get back to you about this. 
I can confirm that the setup is now a lot smoother. :)
