### ISSUE TITLE
Update doc site branding/colours

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#629]
The curio branding uses purples we should update the branding to match bearer.com.

- [x] logo updated #631
- [x] colours updated https://github.com/Bearer/bearer/pull/635

**Comment by Ombe-b** [comment]
theme: {
colors: {
transparent: "transparent",
current: "currentColor",
black: "#0C0C0C",
white: "#FFFFFF",
code: "hsl(243,27%,35%)",

neutral: {
600: "hsl(222, 47%, 11%)",
500: "#3D3D3D”,
400: "#939393”,
300: “#D4D4D4",
200: "#EAEAEA”,
100: "#F6F6F6”,
},

 main: {
100: "#EEE8FD",
200: "#DBD0FB",
300: "#9472E2",
400: "#7043ED",
DEFAULT: "#7043ED",
500: "#4C14E9",
600: "#3D10BA",
700: "#1E065F",
  },
    }
