### ISSUE TITLE
False positives with data type detections

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer#674]
## Description & Reproduction

Javascript rules `javascript_lang_exception` and `javascript_lang_logger` trigger if there is a property access in the exception or logger call and the receiver object has data types.

Code sample (pseudo but the structure is represented): 

```javascript
// exception
async function run(err) {
  const resp = await this.getResponse({
    data: {
      name: this.name,
      email: this.email
    }
  })

  if (resp.error != nil) {
    throw new Error(resp.error)
  }

  return data
}
```

```javascript
// logger
async function run(err) {
  const resp = await this.getResponse({
    data: {
      name: this.name,
      email: this.email
    }
  })

  if (resp.error != nil) {
    console.log(resp.error)
  }

  return data
}
```

## Expected Behavior

The rules should not be triggered in these cases since the exception call or logger call do not involve a data type

## Actual Behavior

The rules are triggered

## Further examples

The exception rule is also triggered by the following code (unexpected), which may be a related issue: 

```javascript
const funcAlice = () => {
	return new Promise((resolve, reject) => {})
};

const funcBob = () => {
		let data = {
			email:      'admin@example.com',
			name:       'Administrator',
		};
};

module.exports = function () {
	return funcAlice()
		.then(funcBob)
};
```

And the Ruby Rails session rule (id `ruby_rails_session`) is triggered by the following code, when we wouldn't expect it to trigger: 

```ruby
user = User.find_by_name(params[:username])
session[:user_id] = user.id 
```

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: current `main`
sha: 84fd36b5aa477747e508c2a32c48ab54238ad304
```

**Comment by didroe** [comment]
We ran into some complexity in the attempted fix in https://github.com/Bearer/bearer/pull/751. Some of the problems were fixed but there are still problems with the nodes which are reported for matches, and matching arguments of calls.

We need to step back and define the behaviour for each case before fixing this.
