### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [Bearer/bearer#689]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/Bearer/bearer/blob/master/packages/cli/package.json#L37

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same for `path` and `os`.

**Comment by tanguyantoine** [comment]
Good catch, thank you for pointing this.

**Comment by tanguyantoine** [comment]
I'm wondering if an eslint rule would be worth it ;-)

**Comment by tanguyantoine** [comment]
published as `1.4.1`
