### ISSUE TITLE
ruby_lang_hardcoded_secret matches empty string

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#716]
## Description & Reproduction

would not expect ruby_lang_hardcoded_secret to match on empty string since there is no secret there 

```
git clone https://github.com/sharetribe/sharetribe ; 
bearer scan --only-rule=ruby_lang_hardcoded_secret ./sharetribe
```

```
CRITICAL: Hard-coded secret detected. [CWE-798]
https://docs.bearer.com/reference/rules/ruby_lang_hardcoded_secret
To skip this rule, use the flag --skip-rule=ruby_lang_hardcoded_secret

File: ./sharetribe/app/services/person/omniauth_service.rb:252

 252             strategy.options[:client_secret] = ""
```

## Expected Behavior

does not match

## Actual Behavior

matches

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 0.00.0
sha: 23b10384c1300dead9e8c5a023da3bdaf8ee4131
```

**Comment by cfabianski** [comment]
That's the PR but I don't know if that's really a bug. 
The fact that it indicates that the password is hardcoded is interesting. If we set a password to empty, then we expose ourselves to a page being accessible even though we meant to create some sort of protection. 
I think it's even worse than having it hardcoded tbh
