### ISSUE TITLE
ruby_lang_hardcoded_secret on hash match hash line is matched not password line

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#717]
## Description & Reproduction

When a match is detected the highlighted line is incorrect

```
git clone https://github.com/sharetribe/sharetribe
bearer scan --only-rule=ruby_lang_hardcoded_secret ./sharetribe
```

```
CRITICAL: Hard-coded secret detected. [CWE-798]
https://docs.bearer.com/reference/rules/ruby_lang_hardcoded_secret
To skip this rule, use the flag --skip-rule=ruby_lang_hardcoded_secret

File: ./sharetribe/features/step_definitions/user_steps.rb:80

 80     defaults = {
 81       password: "testi",
 82       given_name: "Test",
 83       family_name: "Person"
  	...
 84     }
 ```
 In this example line 80 is indicated as the problem line

## Expected Behavior

indicates line 81

## Actual Behavior

indicates line 80

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 0.00.0
sha: 23b10384c1300dead9e8c5a023da3bdaf8ee4131
```

**Comment by cfabianski** [comment]
Fixed in https://github.com/Bearer/bearer/commit/ada10d76604ce1859a7e5d2f462c848ee9ec859f

**Comment by cfabianski** [comment]
And confirmed 

<img width="789" alt="image" src="https://user-images.githubusercontent.com/110196/222729785-057621db-a4a6-4ab9-933c-7737d02e0c6b.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/110196/222729805-a0e4863c-3456-4100-a379-1828826f0023.png">
