### ISSUE TITLE
[BUG] - node/js package sends the clientId to the distant-API

### ISSUE THREAD

**Issue by Frenchcooc** [Bearer/bearer#731]
**Describe the bug**
The `clientId` used to authenticate a query from the client-side, is passed alongside the query string, which is then passed to the API.

With some API (e.g. Google Sheets), this throw the error below:
```json
{
  "error": {
    "code":400,
    "message":"Invalid JSON payload received. Unknown name \"clientId\": Cannot bind query parameter. Field 'clientId' could not be found in request message.",
    "status":"INVALID_ARGUMENT",
    "details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"description":"Invalid JSON payload received. Unknown name \"clientId\": Cannot bind query parameter. Field 'clientId' could not be found in request message."}]}]}
}
```

**Package concerned**

`@bearer/js` 

**To Reproduce**
1. Add the Google Sheets API to your Bearer account
1. Make sure you allow requests from the client-side (in the settings)
1. Follow the steps on the instructions page (credentials/connection)
3. Copy/paste the JavaScript snippet from the instructions
4. See error above.

**Expected behavior**
The `clientId` should be passed in a `Bearer-Client-ID` header that is not passed to the distant-api.

**Screenshot**

This is a log that I can see for a client-side API call to Google Sheets API:
![Capture d’écran 2019-09-04 à 14 02 56](https://user-images.githubusercontent.com/3255133/64253107-d7ea4800-cf1c-11e9-8972-8468c40f9e35.png)

**Comment by cfabianski** [comment]
Fixed in version 1.13.4
