### ISSUE TITLE
[BUG] - bearer/js connect button is failing silently

### ISSUE THREAD

**Issue by Frenchcooc** [Bearer/bearer#733]
**Describe the bug**

**Package concerned**

`@bearer/js` 

**To Reproduce**
1. Create an index.html and copy/paste the following code
2. Click on the Connect button
3. The OAuth is failing rapidly because the credentials passed are wrong. 

```html
<!DOCTYPE html>

<body>
  <button onclick="myConnectButton()">Connect to Trello</button>
</body>

<script src="https://cdn.jsdelivr.net/npm/@bearer/js/lib/bearer.production.min.js"></script>
<script>
  const bearerClient = bearer('8a7d25f3e7853201b4ff5245c926502f0031f5771580144ff3', {
    integrationHost: 'https://int.staging.bearer.sh'
  })

  // Right setup ID, but with bad credentials inside
  const setupId = '7f2f82dc-cfde-45f8-bc67-11fec772e74e'

  function myConnectButton() {
    bearerClient
      .connect('trello', setupId) // Integration UUID
      .then(({ authId }) => {
        // Use this authId like bearer.auth(authId).get(..
        console.log('AUTH_ID for this user', authId)
      })
      .catch(console.error)
  }
</script>

```

**Expected behavior**
The `catch` shall be called and the console shall output the error 

**Screenshots**
![error-connect](https://user-images.githubusercontent.com/3255133/64803079-f4712a80-d583-11e9-945d-0fc41ed847c8.gif)

**Comment by cfabianski** [comment]
related: https://github.com/Bearer/bug-tracker/issues/1
