### ISSUE TITLE
Handle minified JS files better

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#747]
Currently minifed JS files can cause very large output on the security report and are not of much use.

Also we might want to ignore some of these files as they could be external or compiled?

**Comment by cfabianski** [comment]
https://github.com/ChromeDevTools/devtools-frontend/blob/main/front_end/models/text_utils/TextUtils.ts#L336

**Comment by cfabianski** [comment]
https://mariusschulz.com/blog/detecting-minified-javascript-code
