### ISSUE TITLE
Rule gets triggered twice: Password length (< 8) requirement is too short. [CWE-521]

### ISSUE THREAD

**Issue by yshmarov** [Bearer/bearer#761]
## Description & Reproduction

using devise, scanned this repo: https://github.com/corsego/corsego/
and the same devise exception gets raised twice:

<img width="761" alt="Screenshot 2023-03-09 at 17 43 56" src="https://user-images.githubusercontent.com/13472945/224092762-f5d39b41-b580-4ce5-8c49-f1baf4a054b9.png">

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 1.0.0
sha: 77d701df4e71763ec6677aea09fcb1e62e97bf0d
```

**Comment by elsapet** [comment]
Thanks for raising this one @yshmarov 🙏
