### ISSUE TITLE
Using passwordless for authentication

### ISSUE THREAD

**Issue by yshmarov** [Bearer/bearer#762]
## Description & Reproduction

passwordless = magic link login (instead of devise). ran on this repo: https://github.com/yshmarov/insta2blog.com

that's not a hard-coded secret right here, just a path:

<img width="771" alt="Screenshot 2023-03-09 at 17 46 03" src="https://user-images.githubusercontent.com/13472945/224093329-e86579ef-413b-465e-97f3-b515fbe14c51.png">

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 1.0.0
sha: 77d701df4e71763ec6677aea09fcb1e62e97bf0d
```

**Comment by yshmarov** [comment]
Must be a duplicate of https://github.com/Bearer/bearer/issues/760

**Comment by elsapet** [comment]
Thanks for raising 🙏 
Addressed by https://github.com/Bearer/bearer/pull/771
