### ISSUE TITLE
Load rules from external repository

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer#799]
We currently need to release a new version every time we write a new rule. This is tiresome and prevents quick iteration. Instead, we could move rules (the rule YAML files) to their own repository: https://github.com/Bearer/bearer-rules

This would simplify the way to customize rules as you would need to fork only the rules folder rather than the whole bearer repo. 

Some things for consideration: 
- How would the rule integration tests work? 
- What about the documentation? Right now the documentation website includes the documentation of the rules which uses the metadata from the rule files themselves
- How would this relate (if at all) to the current external rule functionality?
  - We would also no longer need to have an external rule folder defined in the config. Instead you just specify which DB you want to use (by default, [github.com/bearer/bearer-rules](http://github.com/bearer/bearer-rules) would be picked up)
  - However, external rule folder may be solving a different problem - for example, it provides a quick way to add a new rule; whereas, forking the rules repo lets us edit existing rules.
- Should we download all the rules each time or can we do with the subset of languages identified at first.
  -  Ideally, we should list all the languages detected at the beginning and download only the rules for these languages (@cfabianski)

Pending tasks

- [ ] Move documentation URLs to bearer-action rule YAML files https://github.com/Bearer/bearer-rules/issues/6
- [ ] Update README.md for bearer-rules repo
- [ ] Documentation around bearer-rules repo and how it is used

**Comment by markmichon** [comment]
Regarding the external rules folder, it could be beneficial to still allow multiple sources. One scenario might be: load built-in, load company specific, load team specific. Not sure if it makes sense to allow external and local sources in the same config setting, but it seems user-hostile to force them to clone the rules repo if they want to add custom rules on top of it.

Regarding docs generation: The data sourcing logic would need to change, however, it shouldn't be too difficult to _fetch_ the files from an external repo(s) via github's API. It also shouldn't hurt the doc site versioning, as a rebuild would fetch the latest rules while keeping the same documentation branch data.

**Comment by elsapet** [comment]
Good point on the external rules folder @markmichon - I think this could benefit from further discussion / reflection. I've updated the description  🙏

**Comment by cfabianski** [comment]
Related https://github.com/Bearer/bearer/issues/782

**Comment by elsapet** [comment]
Closed by https://github.com/Bearer/bearer/pull/827
