### ISSUE TITLE
Docs: Adding "Upgrade" instruction

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#813]
It would be helpful to add an "upgrade/update" instruction page in the doc below the "installation" one:
https://docs.bearer.com/reference/installation/

**Comment by markmichon** [comment]
@cfabianski Do you have any insight on updating via the various methods? I know how to do so for homebrew, but unsure of the rest

**Comment by gmontard** [comment]
@gotbadger maybe?

**Comment by cfabianski** [comment]
**Install Script**

Nothing in particular, just run the command again and it will override the previous one

**Homebrew**

```bash
$ brew update && brew upgrade bearer/tap/bearer
```

**Debian/Ubuntu**

```bash
$ sudo apt-get update
$ sudo apt-get install bearer
```

**RHEL/CentOS**

```bash
$ sudo yum -y update bearer
```

**Docker**

Nothing should be required since it will download the latest
