### ISSUE TITLE
Docs: Show the "dataflow" report

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#815]
After different discussions, it seems a lot of people are interested with the raw "dataflow" report, that is currently hidden in the CLI, and not documentation in the "report" section.

Let's change this.

**Comment by cfabianski** [comment]
We also need to update it in few places [here](https://github.com/Bearer/bearer/blob/main/pkg/flag/report_flags.go) but it should be fairly straightforward (we will need to update some snapshots too)
