### ISSUE TITLE
Blank values for arguments cause unexpected behaviour

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#816]
## Description & Reproduction

This caused an issue with the github action here https://github.com/Bearer/bearer-action/pull/15 as empty argument overrides defaults

## Expected Behavior

when an arugment is empty it is not applied or used

## Actual Behavior

`--only-rule=` seems to apply all rules

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 1.1.0
sha: 165a42876a93e8b92e116b50feea2a7806f5499
```

**Comment by cfabianski** [comment]
It looks like it's doing the right thing.

Specifying `skip-rule=` and `only-rule=` will just skip the options and will load all the rules.
If I specify `skip-rule` or `only-rule` and keep the other one empty, it looks like it respects the arguments I'm passing

**Comment by cfabianski** [comment]
<img width="1932" alt="image (66)" src="https://user-images.githubusercontent.com/110196/228290781-8bd980d1-5a72-495e-92c1-1f5989be424f.png">
<img width="1155" alt="image (65)" src="https://user-images.githubusercontent.com/110196/228290797-5f9dcbd1-cb18-4a0a-9e49-40a3a9fc9d81.png">

**Comment by cfabianski** [comment]
When used with a `bearer.yml` file we reset the `only-rule` and `skip-rule` filters by passing empty strings.
Would need to think a little bit more about it 🤔

**Comment by gotbadger** [comment]
looks like bearer.yml uses an array now so it seems like this is fixed and we accept that https://github.com/Bearer/bearer/issues/816#issuecomment-1487135817 is how this should behave.
