### ISSUE TITLE
Add support for ignoring fingerprints from the config-file

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#817]
We support skipping a finding of a specific rule from within the file but AppSec engineers don't really touch the files themselves and rather they keep an ignore-list in a separate file. 

Option 1: Add those ignores within the bearer.yml
Option 2: Create a separate file and reference it in the bearer.yml

**Comment by elsapet** [comment]
For now, I've implemented option 1 (the simplest option) here: https://github.com/Bearer/bearer/pull/1018

Do we want to look into option 2 at this stage or is option 1 solution sufficient for now? What kind of format would we like this file to have? Should it be a file that Bearer auto-generates for us? 

Also, I think this is the approach of other tools, but to confirm: are we still okay to only show the fingerprints in the JSON / YAML report formats (i.e. not the default security report)?

**Comment by elsapet** [comment]
Closing this as we have decided on the simpler option 1 for the time being. 
We can look at adding a separate and / or optional ignore file down the line, if needed.
