### ISSUE TITLE
docs: github action example uses hardcoded version

### ISSUE THREAD

**Issue by markmichon** [Bearer/bearer#820]
The [github action example](https://docs.bearer.com/guides/github-action/) has v1 hardcoded, but should use bearer/bearer-action@main instead.

Locations that need updates:
- [ ] ~~[github action guide](https://docs.bearer.com/guides/github-action/)~~
- [ ] ~~[bearer-action readme](https://github.com/Bearer/bearer-action)~~
- [x] https://github.com/Bearer/railsgoat
- [x] https://github.com/Bearer/NodeGoat
- [x] https://github.com/Bearer/bear-publishing

**Comment by gotbadger** [comment]
Really we should be using v1 everywhere will update the example repos to match this.

**Comment by gotbadger** [comment]
done
