### ISSUE TITLE
Error message about loading bearer.yml is recieved when not trying to load a config file

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#840]
## Description & Reproduction

when running `bearer scan .` I get the following message

```
Couldn't find config file bearer.yml or bearer.yml
```

## Expected Behavior
Do not receive a message

## Actual Behavior
we get a message saying it could not load the file

## Possible Fix
We should try to load the file by default but if we dont find it dont bother the user because they didn't actually ask to use one.

Also the repitition of bearer.yml seems a bit strange

Proably related to this change https://github.com/Bearer/bearer/pull/830

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: main
sha: 089310d147862a14237345fc20e8eaba0a608e9f
```

**Comment by cfabianski** [comment]
Fixed by #843
