### ISSUE TITLE
rule: `express_insecure_cookie` false positive

### ISSUE THREAD

**Issue by markmichon** [Bearer/bearer#845]
## Description & Reproduction
Scanning https://github.com/freeCodeCamp/freeCodeCamp and ran into what I think might be false positives on `express_insecure_cookie`.

The following rule trigger occurs:
```
MEDIUM: Missing secure options for cookie detected. [CWE-1004, CWE-614]
https://docs.bearer.com/reference/rules/express_insecure_cookie
To skip this rule, use the flag --skip-rule=express_insecure_cookie

File: api-server/src/server/middlewares/csurf.js:11

 11     cookie: { ...csrfOptions, httpOnly: true }
```

## Expected Behavior

Here's the code for the file:
```js
export const csrfOptions = {
  domain: process.env.COOKIE_DOMAIN || 'localhost',
  sameSite: 'strict',
  secure: process.env.FREECODECAMP_NODE_ENV === 'production'
};

export default function getCsurf() {
  const protection = csurf({
    cookie: { ...csrfOptions, httpOnly: true }
  });

// ...
```
The rule wants to see `secure: true`, but in this case that detail is behind a few layers of conditions.
The scanner should notice that `...csrfOptions` is expanded to include the config options, and should then notice that the env is setting `secure` to true in prod. End result being: the rule won't trigger.

## Actual Behavior
The rule triggers as shown above.

Unsure if the cause is the lack of option expansion or the use of env variables. 

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 1.1.0 (also tested on main)
sha: xxx
```

**Comment by cfabianski** [comment]
Link to file https://github.com/freeCodeCamp/freeCodeCamp/blob/main/api-server/src/server/middlewares/csurf.js
