### ISSUE TITLE
Doc: add a diagram for bearer workflow displaying

### ISSUE THREAD

**Issue by abserari** [Bearer/bearer#852]
![image](https://user-images.githubusercontent.com/32089134/229532432-f75946d8-2bf0-47ad-b2b8-0bbf77b3c336.png)

I tried to draw this workflow chart according to my understanding. He mainly has the following shortcomings:

1. I have not completely read the entire code, so I will modify it many times.
2. The hand-drawn style used may appear informal.

**Comment by cfabianski** [comment]
Thank you @abserari for this contribution. We will have a closer look and see how we could make it part of the documentation in the best way

**Comment by cfabianski** [comment]
@abserari we came up with this diagram with Mermaid but thanks very much for your initiative! I hope it helps clarifying the process to others and make contributions easier! Let us know what you think
