### ISSUE TITLE
improve http insecure rules for js and ruby

### ISSUE THREAD

**Issue by vjerci** [Bearer/bearer#867]
## Description & Reproduction

By parsing battle test results we have found that we have some amount of false positive detections for using http instead of https.
The thing is most of these detections should be easy to ignore since they start either with http://localhost or http://127.0.0.1

## Expected Behavior

Ignore http insecure detections that start with localhost or 127.0.0.1

**Comment by cfabianski** [comment]
@vjerci Should be a matter of updating this https://github.com/Bearer/bearer/blob/dc35d997c67c1719fae83b4adc77e4f4b7476b6f/new/detector/implementation/generic/insecureurl/insecureurl.go#L39-L41 right?

**Comment by vjerci** [comment]
yeah seems so. will fix it tomorrow.
