### ISSUE TITLE
Change "failure" terminology to "finding" 

### ISSUE THREAD

**Issue by gmontard** [Bearer/bearer#882]
Security team are more used to the "finding" terminology than "failure" one.

### Required changes:

In the CLI output, we need to change:
`107 checks, 11 failures, 6 warnings`

To:
`107 checks, 17 findings`

Also, documentation need to be checked though and through (especially examples) and be updated using the "finding" terminology.

**Comment by elsapet** [comment]
@gmontard Aside from the documentation, we also use `Critical Risk Failure`, `High Risk Failure` etc in the Privacy report itself. Do we want to update these to something like `Critical Risk Findings`, etc? 

For example
```
Subject,Data Types,Detection Count,Critical Risk Failure,High Risk Failure,Medium Risk Failure,Low Risk Failure,Rules Passed
User,Fullname,4,0,1,0,0,47
User,Email Address,9,0,6,0,0,42
User,Telephone Number,1,0,0,0,0,48

Third Party,Subject,Data Types,Critical Risk Failure,High Risk Failure,Medium Risk Failure,Low Risk Failure,Rules Passed
Segment,Unknown,"Unknown",0,0,0,0,0
Sentry,User,"Email Address",0,1,0,0,1
```

will become

```
Subject,Data Types,Detection Count,Critical Risk Finding,High Risk Finding,Medium Risk Finding,Low Risk Finding,Rules Passed
User,Telephone Number,1,0,0,0,0,48
User,Fullname,4,0,1,0,0,47
User,Email Address,9,0,6,0,0,42

Third Party,Subject,Data Types,Critical Risk Finding,High Risk Finding,Medium Risk Finding,Low Risk Finding,Rules Passed
Segment,Unknown,"Unknown",0,0,0,0,0
Sentry,User,"Email Address",0,1,0,0,1
```

**Comment by elsapet** [comment]
Closing because all code base changes have been addressed; however as a note there may be screenshots or screen recordings with old terminology. Feel free to re-open if these are to be addressed too 🙏
