### ISSUE TITLE
Provide a way to convert a JSON output into an HTML

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#918]
We could build another tool that would be responsible from converting the JSON output to an HTML output to ease an offline processing of the report.

**Comment by cfabianski** [comment]
Interesting reference https://github.com/snyk/snyk-to-html

**Comment by MostlyGenius** [comment]
Can you assign this to me?  Looks like a good project to hone my skills. Thanks

**Comment by gotbadger** [comment]
@MostlyGenius feel free to give it a go we are not intending to do this ourselves in the short term so let us known what you come up with. 

Happy to see any external contribution to to enhance the project.

**Comment by gotbadger** [comment]
Havent heard anything from @MostlyGenius so unassigning

**Comment by gotbadger** [comment]
Since this issue was first created we now have better output formating internals so we can quite possibly generate the HTML directly as an output
