### ISSUE TITLE
CLI reports javascript_express_reduce_fingerprint wrongly

### ISSUE THREAD

**Issue by ali-habibzadeh** [Bearer/bearer#922]
## Description & Reproduction
I have an express which uses helmet using the following pattern:
`app.use(helment());`
`app.use(hidePoweredBy());`

And I am sure I am not sending the x-powered-by header as a result.

## Expected Behavior

I shouldn't see any error to do with this header.

## Actual Behavior

I get:

MEDIUM: Security misconfiguration detected. [CWE-693]
https://docs.bearer.com/reference/rules/javascript_express_reduce_fingerprint
To skip this rule, use the flag --skip-rule=javascript_express_reduce_fingerprint

```
bearer version: 1.3.1
sha: 166c7dbb686dec9f49e1240b210d611dee8c9d79
```

**Comment by cfabianski** [comment]
Thanks @ali-habibzadeh 
That’s probably because you are importing directly. I’ll take a look but it is likely due to #873 

We can add an easy workaround I think for the time being

**Comment by ali-habibzadeh** [comment]
here is the module that uses helment

```
import helment, {
  contentSecurityPolicy,
  crossOriginEmbedderPolicy,
  crossOriginOpenerPolicy,
  crossOriginResourcePolicy,
  dnsPrefetchControl,
  frameguard,
  hidePoweredBy,
  hsts,
  ieNoOpen,
  noSniff,
  originAgentCluster,
  permittedCrossDomainPolicies,
  referrerPolicy,
  xssFilter,
} from "helmet";

import { Express } from "express";

export const addHelment = (app: Express) => {
  app.use(helment());
  app.use(hidePoweredBy());
};
```
Then in the main.ts

```
const bootstrapServer = async () => {
const expressApp = express();
addHelment(expressApp);
.... rest of the shebang 
```

**Comment by cfabianski** [comment]
A new version of the rules has been released. If you could give it a go and let me know if that fixes it @ali-habibzadeh for you :)

**Comment by ali-habibzadeh** [comment]
@cfabianski It is still broken and finds the same issues. Since then I have refactored and now the actual addition of helment config happens in a different file like this:

```typescript
export const addHelmet = (app: Express) => {
  app.use(helment()); // <------ javascript_express_helmet_missing
  app.use(contentSecurityPolicy());
  app.use(crossOriginEmbedderPolicy());
  app.use(crossOriginOpenerPolicy());
  app.use(crossOriginResourcePolicy());
  app.use(dnsPrefetchControl());
  app.use(frameguard());
  app.use(hidePoweredBy()); // <------ javascript_express_reduce_fingerprint
  app.use(hsts());
  app.use(ieNoOpen());
  app.use(noSniff());
  app.use(originAgentCluster());
  app.use(permittedCrossDomainPolicies());
  app.use(referrerPolicy());
  app.use(xssFilter());
};
```

Which bearer can't find. But also begs the question, does Bearer ignore the rest of the checks? since I can't see a warning about the other ones.

This was done wit Bearer 1.8.1

**Comment by cfabianski** [comment]
Thanks @ali-habibzadeh for the feedback.
I've tested and issued a PR to improve our detections with helmet [here](https://github.com/Bearer/bearer-rules/pull/77)

I couldn't reproduce the issue with `hidePoweredBy()` (in my test file I have https://github.com/Bearer/bearer-rules/pull/77/files#diff-3f237b6e79db22a2945cd4d38cbc0b925e5b2609a6ab429079737c1b5e0def38 and the snapshots comes back empty https://github.com/Bearer/bearer-rules/pull/77/files#diff-4aa2811c32e676e34c9bf9fba5f3f0ac4969f3c89fc16325db44dc0730bb551f) :/

NB: it wouldn't detect if there is a typo like in your example `helment()` vs `helmet()` (not sure that's the case in your code base or not)

I'll reopen for now

**Comment by cfabianski** [comment]
Closing as we made loads of improvement to handle that case. Thanks @ali-habibzadeh
