### ISSUE TITLE
Publish canary linux/mac packages

### ISSUE THREAD

**Issue by didroe** [Bearer/bearer#924]
We currently only publish linux (eg. RPM/DEB) and brew packages for non-canary releases. This makes it hard to test those packages without doing a production release first.

We should publish the packages either with a version number that's ignored by default (if possible), or publish them to a separate repository (/ brew formula).

**Comment by gotbadger** [comment]
closing this based on our discussion to use rpm direct or ideally https://github.com/Bearer/bearer/issues/503
